#!/usr/bin/env node
/*
 * build-strokes.js — 把 50 个笔迹 json + 字源表 CSV 打包成 web/js/strokes-bundle.js
 *
 * 输入（平台无关、已在磁盘）：
 *   ../data/strokes/u<hex>.json                       （Arphic Public License，笔迹中位线）
 *   ../design/gdd/character-source-table-50.md        （含 ```csv 机器可读块：pinyin + 释义 + 配色）
 *
 * 输出：
 *   js/strokes-bundle.js  ——
 *     window.STROKE_DATA = { "<HEX>": <stroke json>, ... }
 *     window.CHAR_META   = { "<HEX>": {char,pinyin,meaning,cluster,main_color,accent_color,...}, ... }
 *     同时 module.exports（供 node 测试 require）。
 *   禁止 fetch / ES module import —— 用 <script> 全局变量，file:// 双击即可用。
 *
 * 运行：用管理版 node 跑（见 README）。
 */
'use strict';

var fs = require('fs');
var path = require('path');

var ROOT = path.resolve(__dirname, '..');                 // D:/Fire/儿童识字游戏
var STROKE_DIR = path.join(ROOT, 'data', 'strokes');
var META_MD = path.join(ROOT, 'design', 'gdd', 'character-source-table-50.md');
var OUT = path.join(__dirname, 'js', 'strokes-bundle.js');

// 从 GDD markdown 的 ```csv 块解析字源表
function readMetaFromMarkdown() {
  var txt = fs.readFileSync(META_MD, 'utf8');
  var m = txt.match(/```csv\s*\n([\s\S]*?)```/);
  if (!m) throw new Error('CSV block not found in ' + META_MD);
  var lines = m[1].split(/\r?\n/).filter(function (l) { return l.trim() !== ''; });
  var meta = {};
  // 列（9 列）：unicode_hex,char,pinyin,meaning,cluster,glyph_association,feature_desc,main_color,accent_color
  for (var i = 0; i < lines.length; i++) {
    var parts = lines[i].split(',');
    if (parts.length < 9) continue;
    var hex = parts[0].trim().toUpperCase();
    if (!/^[0-9A-F]+$/.test(hex)) continue; // 跳过表头等
    meta[hex] = {
      unicode_hex: hex,
      char: parts[1].trim(),
      pinyin: parts[2].trim(),
      meaning: parts[3].trim(),
      cluster: parts[4].trim(),
      glyph_association: parts[5].trim(),
      feature_desc: parts[6].trim(),
      main_color: parts[7].trim(),
      accent_color: parts[8].trim()
    };
  }
  return meta;
}

function main() {
  var meta = readMetaFromMarkdown();

  var files = fs.readdirSync(STROKE_DIR).filter(function (f) {
    return /^u[0-9a-fA-F]+\.json$/.test(f);
  });
  files.sort();

  var STROKE_DATA = {};
  var CHAR_META = {};
  var errors = [];
  var count = 0;

  files.forEach(function (f) {
    var full = path.join(STROKE_DIR, f);
    var raw;
    try { raw = fs.readFileSync(full, 'utf8'); }
    catch (e) { errors.push(f + ': read fail (' + e.message + ')'); return; }

    var obj;
    try { obj = JSON.parse(raw); }
    catch (e) { errors.push(f + ': JSON parse error (' + e.message + ')'); return; }

    var hex = (obj.unicode_hex || '').toUpperCase();
    if (!hex) { errors.push(f + ': missing unicode_hex'); return; }
    if (!obj.strokes || !Array.isArray(obj.strokes) || obj.strokes.length === 0) { errors.push(f + ': no strokes'); return; }
    if (!Array.isArray(obj.order)) { errors.push(f + ': missing order'); return; }
    if (!Array.isArray(obj._render_center) || obj._render_center.length !== 2) { errors.push(f + ': missing _render_center'); return; }

    STROKE_DATA[hex] = obj;

    var cm = meta[hex];
    if (cm) {
      CHAR_META[hex] = cm;
    } else {
      // 兜底：资产缺元数据也不阻塞，用安全占位
      CHAR_META[hex] = {
        unicode_hex: hex,
        char: obj.char || '',
        pinyin: '',
        meaning: '',
        cluster: '',
        glyph_association: '',
        feature_desc: '',
        main_color: '#FFC93C',
        accent_color: '#6FC3E4'
      };
      errors.push(f + ': no CHAR_META, used placeholder');
    }
    count++;
  });

  var banner =
    '/* AUTO-GENERATED by build-strokes.js — do not edit by hand.\n' +
    ' * Sources: data/strokes/u*.json (Arphic Public License) + design/gdd/character-source-table-50.md\n' +
    ' * Classic script: sets window.STROKE_DATA / window.CHAR_META; also module.exports.\n' +
    ' * NO fetch / NO ES module — runs from file:// by double-click. */\n';

  var body =
    '(function () {\n' +
    '  var STROKE_DATA = ' + JSON.stringify(STROKE_DATA) + ';\n' +
    '  var CHAR_META = ' + JSON.stringify(CHAR_META) + ';\n' +
    '  if (typeof window !== "undefined") {\n' +
    '    window.STROKE_DATA = STROKE_DATA;\n' +
    '    window.CHAR_META = CHAR_META;\n' +
    '  }\n' +
    '  if (typeof module !== "undefined" && module.exports) {\n' +
    '    module.exports = { STROKE_DATA: STROKE_DATA, CHAR_META: CHAR_META };\n' +
    '  }\n' +
    '})();\n';

  fs.writeFileSync(OUT, banner + body, 'utf8');

  console.log('build-strokes: parsed ' + count + ' stroke files.');
  console.log('build-strokes: ' + Object.keys(CHAR_META).length + ' CHAR_META entries linked.');
  console.log('build-strokes: output -> ' + OUT);
  if (errors.length) {
    console.log('build-strokes: WARNINGS (' + errors.length + '):');
    errors.forEach(function (e) { console.log('  - ' + e); });
  } else {
    console.log('build-strokes: no parse errors.');
  }
  if (count !== 50) console.log('build-strokes: NOTE expected 50 chars, got ' + count);
}

main();
